### ISSUE TITLE
Make the current min domain value for log scale configurable

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#897] opened 2020-11-10 17:27 UTC
**Describe the solution you'd like**
The current log scale limit the rendering to a minimum value of 1 or -1. This avoids over-emphasizing near-zero data.
This value was chosen to align with the current implementation with vislib/Kibana.
This can be a no-go solution for data where small components are important.

The idea is to make this constant configurable via `theme` allowing users to specify a different minimum limit.

**Describe alternatives you've considered**
Using the [symlog](https://www.researchgate.net/publication/233967063_A_bi-symmetric_log_transformation_for_wide-range_data) instead, already available in d3, but there is a current issue in d3 that prevents rendering good ticks on that scale.

**Additional context**
This request comes after the fixing the rendering of negative values on area/lines.

**Comment by nickofthyme** [comment] 2021-02-03 17:30
duplicate of #916

**Closed by nickofthyme** 2021-02-03 17:30 UTC
Labels: :axis, :data, enhancement
