### ISSUE TITLE
scrollbar for data of the x axis

### ISSUE THREAD

**Issue by tilman** [elastic/elastic-charts#1252] opened 2021-07-14 13:11 UTC
**Is your feature request related to a problem? Please describe.**
For a series chart (like barchart or linechart) it would be great to be able to scroll through the provided data. This would greatly improve the UX if a lot of data is available but the plot area is very limited.

**Describe the solution you'd like**
Ideally a simplified chart with scroll ui elements is placed below the chart like in this figure:
![](https://www.mathworks.com/matlabcentral/mlc-downloads/downloads/submissions/14984/versions/4/screenshot.jpg)

Alternativly  a simple scroll bar or [elastic UI dual range slider](https://elastic.github.io/eui/#/forms/range-sliders#dual-range) could be placed below the plot area.

**Describe alternatives you've considered**
I have tried to place the `EuiDualRange` inside the `Chart` component. But it seems that no custom components are working inside the `Chart` component. Is that right or is there a workaround?

**Checklist**

Delete any items that are not applicable to this feature request.
- [x] this request is checked against already exist requests

**Comment by markov00** [comment] 2021-07-16 16:54
>I have tried to place the EuiDualRange inside the Chart component. But it seems that no custom components are working inside the Chart component. Is that right or is there a workaround?

@tilman you are right, you can only use Chart components within the `<Chart>` one. The current set of components act as a bridge between  the chart configuration (described through these components) and the internal logics. We don't render/use/accept external components (except for HOC of the charts ones).
If you want to use the `EuiDualRange` you can probably just use them outside but I perfectly understand that this doesn't provide the desired behaviour.

It's a duplicate of #879 so I will close this issue and we can continue the discussion in #879

**Closed by markov00** 2021-07-16 16:54 UTC
Labels: enhancement
