### ISSUE TITLE
[Heatmap] Color with 0% opacity fallbacks to "default" red color

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#1263] opened 2021-07-21 15:48 UTC
**Describe the bug**
When passing a 8 digits HEX color (classic HEX 6-digits + alpha channel), when the alpha channel is `0` the color seems to be ignored and the fallback `red` color is used.

**To Reproduce**

1. Pass the following `colors={}` props to the Heatmap component: `["#6092c000", "#6092c000", "#a8bfda", "#ebeff5", "#ecb385", "#e7664c"]`
2. Watch the first 2 buckets get colored in `red`

Apparently the bug does not appear when using the `rgba` notation.

**Expected behaviour**

Transparent color should appear.

**Screenshots**

<img width="981" alt="Screenshot 2021-07-21 at 15 52 36" src="https://user-images.githubusercontent.com/924948/126518917-f4b0ee16-7bac-4a1d-aa62-2fcb377cb469.png">

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/106419

**Comment by nickofthyme** [comment] 2021-07-21 16:01
Interesting. So you'd expect it to allow a `transparent` color or prevent transparent color selection?

**Comment by dej611** [comment] 2021-07-21 16:26
I think it should allow the `transparent` color.
But more in general be consistent with the different notations: `rgba` transparent is accepted but `hex` transparent is replaced 😅

**Comment by nickofthyme** [comment] 2021-07-21 19:33
Totally! Got it thanks!

**Comment by nickofthyme** [comment] 2021-07-22 17:14
It appears that the `getColor` function cannot handle hex values color strings with an alpha channel. Might be a related issue.

```ts
getColor('#00000000') // => {r: NaN, g: NaN, b: NaN, opacity: 0}
getColor('#000000') // =>  {r: 0, g: 0, b: 0, opacity: 1}
```

https://github.com/elastic/elastic-charts/blob/f3f8d35be850298311d01884f986aacf58b0a53b/packages/charts/src/common/color_library_wrappers.ts#L57-L76

**Comment by dej611** [comment] 2021-07-26 15:18
Maybe related to this https://github.com/d3/d3-color/issues/52 

The only solution I found is to pass thru `chroma-js` to extract the rgba raw values and use then the `d3Rgb` call to have the correct result: `d3Rgb(chroma(cssColorSpecifier).rgba())`.

Otherwise a special detection branch to return the `transparent` color.

**Comment by nickofthyme** [comment] 2021-07-28 16:38
This appears to be broken in `33.0.2` but I cannot reproduce it in our `master` branch. I'll run a release and make sure the latest release fixes before closing.

https://codesandbox.io/s/lucid-cache-6zlmm?file=/src/App.tsx

**Closed** 2021-07-29 12:56 UTC
Labels: :Lens, :heatmap, Impact:High, bug, good first issue, kibana cross issue
