### ISSUE TITLE
[Waffle] legend labels have some issue when they are number-like

### ISSUE THREAD

**Issue by alexwizp** [elastic/elastic-charts#1513] opened 2021-12-01 12:00 UTC
**Describe the bug:**
This issue is based on https://github.com/elastic/kibana/pull/119339#pullrequestreview-815143509

**Summary:**
legend labels have some issue when they are number-like?

String categories make a rational use of the space for the legend:

<img width="768" alt="Screenshot 2021-11-24 at 17 12 06" src="https://user-images.githubusercontent.com/924948/143276278-b9ee9fc5-9acd-44cb-a4a5-e6e84c2d898b.png">

Number-like don't:

<img width="763" alt="Screenshot 2021-11-24 at 17 11 48" src="https://user-images.githubusercontent.com/924948/143276309-d2442390-9712-4b65-9a86-b0c3f48018b8.png">

**Comment by ghudgins** [comment] 2021-12-09 14:26
Closing this as a duplicate of https://github.com/elastic/elastic-charts/issues/1511

**Closed by ghudgins** 2021-12-09 14:26 UTC
Labels: bug, :partition, :Lens, Impact:Low
