### ISSUE TITLE
externalPointerEvents doesn't trigger the legend extra value update

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#946] opened 2020-12-09 23:47 UTC
**Describe the bug**
If `externalPointerEvents` `tooltip` visiblility is set to false, the legend extra value is no longer updated

**To Reproduce**
1. Go to https://codesandbox.io/s/loving-poincare-0mpuz?file=/src/App.tsx
2. Move the mouse on the top most chart, the bottom chart legend updates its value.
3.  Move the mouse on the bottom most chart, the legend extra value of the top chart doesn't change

**Expected behaviour**
Independentely from the `tooltip` visibility, an external pointer events should update the legend extra value with the actual value computed from the external pointer event x position.

**Version (please complete the following information):**
 - Elastic Charts: current master

**Additional context**
Verified that on version 7.6 and on master in Kibana and seems to be a regression (at least in TSVB that is the only app that use the sync with the hidden tooltip)

**Errors in browser console**
n/a

**Comment by nickofthyme** [comment] 2021-01-26 18:49
Duplicate of https://github.com/elastic/elastic-charts/issues/992

**Closed by nickofthyme** 2021-01-26 18:49 UTC
Labels: :TSVB, :interactions, :tooltip, bug, regression
