### ISSUE TITLE
Breaking change between 21.1.0 and 21.3.2

### ISSUE THREAD

**Issue by timroes** [elastic/elastic-charts#830] opened 2020-09-22 10:11 UTC
There has been an actual breaking change in API between those versions. Earlier the `props` passed into a `customTooltip` component in the setting would have `props.values[0].value` being the formatted string, now it's the raw value and `.formattedValue` is the formatted string. The behavior of course makes imho more sense that way, but it was nevertheless an API breakage.

It could have been caused by https://github.com/elastic/elastic-charts/pull/810, but it could also be linked together with some other PRs, that touched tooltip, and this one was just the one introducing `.formattedValue`.

cc @markov00

**Comment by nickofthyme** [comment] 2020-09-22 13:31
@timroes you are correct this was caused by #810, from [the changes below](https://github.com/elastic/elastic-charts/pull/810/files#diff-551c93b1f051b0ef3056c7f06c477471L94-R95) as of [`v21.1.1`](https://github.com/elastic/elastic-charts/releases/tag/v21.1.1)

```diff
-   value: tickFormatter(value, tickFormatOptions),
+   value,    
+   formattedValue: tickFormatter(value, tickFormatOptions),
```

That is entirely my fault, I should have seen that and kept the value as formatted with a new `rawValue` or something.

Do you think I should deprecate all prior versions and make a new major release?

Breaking versions:
- [`v21.1.2`](https://github.com/elastic/elastic-charts/releases/tag/v21.1.2)
- [`v21.2.0`](https://github.com/elastic/elastic-charts/releases/tag/v21.2.0)
- [`v21.3.0`](https://github.com/elastic/elastic-charts/releases/tag/v21.3.0)
- [`v21.3.1`](https://github.com/elastic/elastic-charts/releases/tag/v21.3.1)
- [`v21.3.2`](https://github.com/elastic/elastic-charts/releases/tag/v21.3.2)

**Comment by markov00** [comment] 2020-09-22 13:56
I think that's the only 'clean' way to fix that

**Comment by nickofthyme** [comment] 2020-09-22 15:22
Fixed by https://github.com/elastic/elastic-charts/commit/d0ddc45e2dbfb23bb1d8682b354b5de2b8476fce

**Closed by nickofthyme** 2020-09-22 15:22 UTC
Labels: breaking change

**Comment by nickofthyme** [comment] 2020-09-22 15:34
Updated [release logs](https://github.com/elastic/elastic-charts/releases) to indicate version deprecations and updated release notes for [`v22.0.0`](https://github.com/elastic/elastic-charts/releases/tag/v22.0.0)

![image](https://user-images.githubusercontent.com/19007109/93904153-26e95380-fcbf-11ea-80f3-cd5c4fa5e9f2.png)
