### ISSUE TITLE
Show default value on tooltip when y-axis is null

### ISSUE THREAD

**Issue by cauemarcondes** [elastic/elastic-charts#1139] opened 2021-04-26 16:51 UTC
**Is your feature request related to a problem? Please describe.**
On APM UI we have a two timeseries chart with the same x-axis value but one has `y = 3.9 ms` and the other has `y = null`, in this case, the only value available in the tooltip is the one different than null. I can not set the null value to 0 since that would be incorrect, but I’d like to show something like `previous period: N/A`  in the tooltip.

<img width="1450" alt="Screen Shot 2021-04-26 at 11 27 54" src="https://user-images.githubusercontent.com/55978943/116120722-da6b5980-a68d-11eb-9c60-3c2a1bbacb91.png">

**Describe the solution you'd like**
I would like to be able to set a default value in the tooltip to show null values.

**Describe alternatives you've considered**
Always showing `N/A` would be an alternative.

**Comment by markov00** [comment] 2021-06-12 08:56
Duplicate of #950

**Closed by markov00** 2021-06-12 08:56 UTC
Labels: enhancement
