### ISSUE TITLE
chart with navigator

### ISSUE THREAD

**Issue by lior-fortifieddata** [elastic/elastic-charts#902] opened 2020-11-12 09:46 UTC
Hi, this is not a bug nor feature request but a question:

is there a way to achieve the following like in Kibana?
thanks!

![image](https://user-images.githubusercontent.com/59799643/98923765-bd2a4080-24dc-11eb-9115-07bf63096944.png)

**Comment by markov00** [comment] 2020-11-12 11:55
You can build something similar with two charts and use the brush tool on the lower one to update the upper one with just a portion of data. But this doesn't offer all the capabilities provided by the above example (like drag an edge of the selection and increase or decrease the area)

please subscribe to this issue that describes your request: https://github.com/elastic/elastic-charts/issues/879

**Comment by markov00** [comment] 2021-07-16 16:54
duplicate of #879

**Closed by markov00** 2021-07-16 16:54 UTC
Labels: enhancement
