### ISSUE TITLE
Re-render of Chart makes data disappear

### ISSUE THREAD

**Issue by yannbolliger** [elastic/elastic-charts#1896] opened 2022-12-09 13:03 UTC
**Describe the issue**

If a chart is structured as a component with the `Chart`, the settings, axes, etc. but the series components e.g. the data as `LineSeries` or `AreaSeries` is passed into that component as `children`, then the graphs disappear, when the chart componet re-renders (but not its parent). I.e. when the `Chart`, settings component re-renders but not its children, it somehow forgets them and shows "No data to display".

**To Reproduce**
1. Create a graph structured in two components
2. The parent component (`App`) renders the `BaseGraph` component and passes some series as children to it.
3. The `BaseGraph` renders the `Chart`, axes etc. and renders the series as children into them.
4. Let only the `BaseGraph` re-render.
5. It "forgets" the series and shows "No data to display".

You can see this exact behaviour in [the codesandbox](https://codesandbox.io/s/crazy-babbage-87npy3?file=/src/BaseGraph.tsx). The `BaseGraph` re-renders triggered by the timeout after 3s. Then, the graph disappears.

**Expected behaviour**
The children should be taken into account on the re-render, the graph should be exactly preserved on re-render as none of its props nor state changes.

**Screenshots**
See [codesandbox](https://codesandbox.io/s/crazy-babbage-87npy3?file=/src/BaseGraph.tsx)

**Version (please complete the following information):**
 - OS: macOS 12/13
 - Browser: Firefox, Chrome, ... 
 - Elastic Charts: latest, i.e. `v51.1.1`

**Additional context**
The issue can be circumvented by changing the `key` of the `Chart` on each render. But this adds a noticeable delay (e.g. blank space for a quick moment) on each re-render because the graph is rebuilt/rendered from scratch each time.

**Errors in browser console**
There are no errors in the console when this happens.

**Checklist**

- [ ] The proper **chart type** label has been added (e.g. `:xy`, `:partition`)
- [ ] The proper **feature** labels have been added (e.g. `:interactions`, `:axis`)

**Comment by markov00** [comment] 2022-12-12 08:54
Thanks @yannbolliger this is actually a known issue https://github.com/elastic/elastic-charts/issues/914
This happens because we can't catch children re-renders due to the way we use the `Chart` component life-cycle to pick up  chart changes.
We need to write our own react reconciler to make it works correctly when child components rerenders rehttps://github.com/facebook/react/tree/main/packages/react-reconciler

**Comment by markov00** [comment] 2022-12-13 14:57
Close, duplicate of https://github.com/elastic/elastic-charts/issues/914

**Closed by markov00** 2022-12-13 14:57 UTC
Labels: bug, :all
