### ISSUE TITLE
Explicitly disabling textBorder for XY charts value labels is ignored

### ISSUE THREAD

**Issue by dej611** [elastic/elastic-charts#887] opened 2020-11-02 17:36 UTC
Setting `textBorder: false` as fill for the value labels settings in the XY chart is ignored.

**Comment by markov00** [comment] 2021-07-28 11:57
duplicate of https://github.com/elastic/elastic-charts/issues/1261#issuecomment-886597061

**Closed by markov00** 2021-07-28 11:57 UTC
Labels: :xy, bug, good first issue
