### ISSUE TITLE
Shorter items in long legend list is hidden by the scrollbar

### ISSUE THREAD

**Issue by markov00** [elastic/elastic-charts#895] opened 2020-11-06 16:01 UTC
**Describe the bug**
When displaying a legend with a scrollable list of items, and each item is short, the scrollbar partially covers the labels and make the legend unreadable

**To Reproduce**
1. Go to https://codesandbox.io/s/bold-jackson-p83cc?file=/src/App.tsx

**Expected behaviour**
The legend should account for the scrollbar space if rendered

**Screenshots**
<img width="490" alt="Screenshot 2020-11-06 at 17 01 05" src="https://user-images.githubusercontent.com/1421091/98387449-ae153f80-2051-11eb-8d43-8ac6412a0ea7.png">

**Version (please complete the following information):**
 - Elastic Charts: 24

**Comment by nickofthyme** [comment] 2021-02-10 16:58
Duplicate of #1011

**Closed by nickofthyme** 2021-02-10 16:58 UTC
Labels: :legend, bug
