### ISSUE TITLE
[Heatmap] visualizations don't adjust color values for dark mode

### ISSUE THREAD

**Issue by ghudgins** [elastic/elastic-charts#1335] opened 2021-08-24 22:14 UTC
**Describe the bug**
Heatmap doesn't adapt to the currently running Kibana theme

**To Reproduce**
 - Enable dark mode in Kibana
 - Visit ML anomaly viewer

Expected: Heatmap adapts to theme
Actual: Heatmap does not adapt to theme

Note: Lens works around this by explicitly setting `background` color

![image](https://user-images.githubusercontent.com/5465514/130696974-15c59798-2e90-44b8-bcb3-7e2b9dbec0f6.png)

**Version (please complete the following information):**
 - OS: OSX
 - Browser: chromium edge 92
 - Elastic Charts: version @ Kibana 7.15 BC1

**Kibana Cross Issues**
https://github.com/elastic/kibana/issues/97636

**Checklist**

Delete any items that are not applicable to this issue.

- [X] every related Kibana issue is listed under `Kibana Cross Issues` list
- [X] `kibana cross issue` tag is associated to the issue if any kibana cross issue is present

**Comment by darnautov** [comment] 2021-08-25 07:28
I found out the actual cause. I think this regression was introduced recently. For some reason, `yAxisLabel.fill` and `xAxisLabel.fill` props are ignored

**Comment by nickofthyme** [comment] 2021-08-30 18:46
Lowering impact due to https://github.com/elastic/kibana/pull/110515 as a workaround for `7.15`. This workaround does not close this issue nor the kibana linked issue.

**Closed** 2021-12-15 23:46 UTC
Labels: bug, kibana cross issue, :heatmap, Impact:High
